### ISSUE TITLE
play all 

### ISSUE THREAD

**Issue by sas05** [nuhil/banglaquran.online#2]
it would be great if it gives a button to play all

Regards

**Comment by nuhil** [comment]
Following two generic features have been avoided intentionally:
1. Don't let people to Pause in the middle of a recitation. They should listen to a full verse at any given time.
2. Don't let people to be subconscious after putting the recitation in a continuous loop. They should be conscious while listening to a verse.

Though, will keep these two things to be implemented near future.

**Comment by sas05** [comment]
make sense
